version: '3'

services:
  web:
    build: .
    container_name: my_django_app
    volumes:
      - myproject:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  myproject:
